-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   at:        2018-11-23 17:41:30 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE akce CASCADE CONSTRAINTS;

DROP TABLE dite CASCADE CONSTRAINTS;

DROP TABLE kontakt CASCADE CONSTRAINTS;

DROP TABLE prihlasovaci_udaje CASCADE CONSTRAINTS;

DROP TABLE trida CASCADE CONSTRAINTS;

DROP TABLE trida_akce CASCADE CONSTRAINTS;

DROP TABLE ucitel CASCADE CONSTRAINTS;

CREATE TABLE akce (
    id_akce           NUMBER NOT NULL,
    nazev             VARCHAR2(30) NOT NULL,
    zkratka           CHAR(15),
    pocetdetinaakci   NUMBER NOT NULL,
    popis             VARCHAR2(255) NOT NULL
);

ALTER TABLE akce ADD CONSTRAINT akce_pk PRIMARY KEY ( id_akce );

CREATE TABLE dite (
    id_dite          NUMBER NOT NULL,
    jmeno            VARCHAR2(15) NOT NULL,
    prijmeni         VARCHAR2(20) NOT NULL,
    vek              NUMBER NOT NULL,
    pohlavi          VARCHAR2(5) NOT NULL,
    trida_id_trida   NUMBER NOT NULL
);

ALTER TABLE dite ADD CONSTRAINT dite_pk PRIMARY KEY ( id_dite );

CREATE TABLE kontakt (
    id_kontakt     NUMBER NOT NULL,
    telefon        NUMBER NOT NULL,
    email          VARCHAR2(25),
    ulice          VARCHAR2(30) NOT NULL,
    psc            NUMBER NOT NULL,
    mesto          VARCHAR2(30) NOT NULL,
    dite_id_dite   NUMBER NOT NULL
);

ALTER TABLE kontakt ADD CONSTRAINT kontakt_pk PRIMARY KEY ( id_kontakt );

CREATE TABLE prihlasovaci_udaje (
    id_udaj             NUMBER NOT NULL,
    prihlasovacijmeno   VARCHAR2(30) NOT NULL,
    heslo               VARCHAR2(30) NOT NULL,
    ucitel_id_ucitel    NUMBER NOT NULL
);

CREATE UNIQUE INDEX prihlasovaci_udaje__idx ON
    prihlasovaci_udaje (
        ucitel_id_ucitel
    ASC );

ALTER TABLE prihlasovaci_udaje ADD CONSTRAINT prihlasovaci_udaje_pk PRIMARY KEY ( id_udaj );

CREATE TABLE trida (
    id_trida   NUMBER NOT NULL,
    nazev      VARCHAR2(50) NOT NULL,
    popis      VARCHAR2(255),
    maxvek     NUMBER
);

ALTER TABLE trida ADD CONSTRAINT trida_pk PRIMARY KEY ( id_trida );

CREATE TABLE trida_akce (
    trida_id_trida   NUMBER NOT NULL,
    akce_id_akce     NUMBER NOT NULL
);

ALTER TABLE trida_akce ADD CONSTRAINT rel_trida_akce_pk PRIMARY KEY ( trida_id_trida,
                                                                      akce_id_akce );

CREATE TABLE ucitel (
    id_ucitel        NUMBER NOT NULL,
    jmeno            VARCHAR2(30) NOT NULL,
    prijmeni         VARCHAR2(35) NOT NULL,
    email            VARCHAR2(35) NOT NULL,
    trida_id_trida   NUMBER NOT NULL
);

ALTER TABLE ucitel ADD CONSTRAINT ucitel_pk PRIMARY KEY ( id_ucitel );

ALTER TABLE dite
    ADD CONSTRAINT dite_trida_fk FOREIGN KEY ( trida_id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE kontakt
    ADD CONSTRAINT kontakt_dite_fk FOREIGN KEY ( dite_id_dite )
        REFERENCES dite ( id_dite );

ALTER TABLE prihlasovaci_udaje
    ADD CONSTRAINT prihlasovaci_udaje_ucitel_fk FOREIGN KEY ( ucitel_id_ucitel )
        REFERENCES ucitel ( id_ucitel );

ALTER TABLE trida_akce
    ADD CONSTRAINT rel_trida_akce_akce_fk FOREIGN KEY ( akce_id_akce )
        REFERENCES akce ( id_akce );

ALTER TABLE trida_akce
    ADD CONSTRAINT rel_trida_akce_trida_fk FOREIGN KEY ( trida_id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE ucitel
    ADD CONSTRAINT ucitel_trida_fk FOREIGN KEY ( trida_id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE dite
    ADD CONSTRAINT dite_trida_fk FOREIGN KEY ( trida_id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE kontakt
    ADD CONSTRAINT kontakt_dite_fk FOREIGN KEY ( dite_id_dite )
        REFERENCES dite ( id_dite );

ALTER TABLE prihlasovaci_udaje
    ADD CONSTRAINT prihlasovaci_udaje_ucitel_fk FOREIGN KEY ( ucitel_id_ucitel )
        REFERENCES ucitel ( id_ucitel );

ALTER TABLE trida_akce
    ADD CONSTRAINT rel_trida_akce_akce_fk FOREIGN KEY ( akce_id_akce )
        REFERENCES akce ( id_akce );

ALTER TABLE trida_akce
    ADD CONSTRAINT rel_trida_akce_trida_fk FOREIGN KEY ( trida_id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE ucitel
    ADD CONSTRAINT ucitel_trida_fk FOREIGN KEY ( trida_id_trida )
        REFERENCES trida ( id_trida );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
