-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   at:        2019-01-17 21:33:51 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE akce_skoly (
    id_akce           int auto_increment primary key,
    nazev             VARCHAR(30) NOT NULL,
    zkratka           CHAR(15),
    pocetdetinaakci   INT NOT NULL,
    popis             VARCHAR(255) NOT NULL
);


CREATE TABLE dite (
    id_dite              int auto_increment primary key,
    jmeno                VARCHAR(20) NOT NULL,
    prijmeni             VARCHAR(30) NOT NULL,
    vek                  int NOT NULL,
    pohlavi              CHAR(10) NOT NULL,
    id_trida       int NOT NULL,
    id_kontakt   int
);


CREATE TABLE jidelnicek (
    id_jidelnicek    int auto_increment primary key,
    polivka          VARCHAR(50) NOT NULL,
    hlavni_jidlo     VARCHAR(50) NOT NULL,
    svacina          VARCHAR(50) NOT NULL,
    id_trida   int NOT NULL,
    datum            DATE NOT NULL
);


CREATE TABLE kontakt (
    id_kontakt   int auto_increment primary key,
    telefon      int ,
    email        VARCHAR(150),
    ulice        VARCHAR(40) NOT NULL,
    psc          int NOT NULL,
    mesto        VARCHAR(50) NOT NULL
);


CREATE TABLE rel_trida_akce (
    id_trida   int NOT NULL,
    id_akce     int NOT NULL
);


CREATE TABLE role (
    id_role    int auto_increment primary key,
    druhrole   VARCHAR(30) NOT NULL
);


CREATE TABLE trida (
    id_trida   int auto_increment primary key,
    nazev      VARCHAR(30) NOT NULL,
    maxvek     int NOT NULL,
    popis      VARCHAR(255)
);


CREATE TABLE ucitel (
    id_ucitel        int auto_increment primary key,
    jmeno            VARCHAR(30) NOT NULL,
    prijmeni         VARCHAR(30) NOT NULL,
    id_role     int NOT NULL,
    id_trida   int NOT NULL
);


CREATE TABLE users (
    id_udaj             int auto_increment primary key,
    prihlasovacijmeno   VARCHAR(60) NOT NULL,
    heslo               VARCHAR(35) NOT NULL,
    id_ucitel    int NOT NULL
);

CREATE UNIQUE INDEX users__idx ON
    users (
        id_ucitel
    ASC );


ALTER TABLE dite
    ADD CONSTRAINT dite_kontakt_fk FOREIGN KEY ( id_kontakt )
        REFERENCES kontakt ( id_kontakt );

ALTER TABLE dite
    ADD CONSTRAINT dite_trida_fk FOREIGN KEY ( id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE jidelnicek
    ADD CONSTRAINT jidelnicek_trida_fk FOREIGN KEY ( id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE rel_trida_akce
    ADD CONSTRAINT rel_trida_akce_akce_fk FOREIGN KEY ( id_akce )
        REFERENCES akce ( id_akce );

ALTER TABLE rel_trida_akce
    ADD CONSTRAINT rel_trida_akce_trida_fk FOREIGN KEY ( id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE ucitel
    ADD CONSTRAINT ucitel_role_fk FOREIGN KEY ( id_role )
        REFERENCES role ( id_role );

ALTER TABLE ucitel
    ADD CONSTRAINT ucitel_trida_fk FOREIGN KEY ( id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE users
    ADD CONSTRAINT users_ucitel_fk FOREIGN KEY ( id_ucitel )
        REFERENCES ucitel ( id_ucitel );

		
		-------------------------------------------------------
ALTER TABLE dite
    ADD CONSTRAINT dite_kontakt_fk FOREIGN KEY ( id_kontakt )
        REFERENCES kontakt ( id_kontakt );

ALTER TABLE dite
    ADD CONSTRAINT dite_trida_fk FOREIGN KEY ( id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE jidelnicek
    ADD CONSTRAINT jidelnicek_trida_fk FOREIGN KEY ( id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE rel_trida_akce
    ADD CONSTRAINT rel_trida_akce_akce_fk FOREIGN KEY ( id_akce )
        REFERENCES akce ( id_akce );

ALTER TABLE rel_trida_akce
    ADD CONSTRAINT rel_trida_akce_trida_fk FOREIGN KEY ( id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE ucitel
    ADD CONSTRAINT ucitel_role_fk FOREIGN KEY ( id_role )
        REFERENCES role ( id_role );

ALTER TABLE ucitel
    ADD CONSTRAINT ucitel_trida_fk FOREIGN KEY ( id_trida )
        REFERENCES trida ( id_trida );

ALTER TABLE users
    ADD CONSTRAINT users_ucitel_fk FOREIGN KEY ( id_ucitel )
        REFERENCES ucitel ( id_ucitel );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             1
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
